apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: prod-app
        image: dockwithvamsee/multibranch-prod-app:build-10
        ports:
        - containerPort: 5000
